Hcxpcaptool is deprecated and replaced with Hcxpcapngtool * Since hcxpcaptool is deprecated and replaced with hcxpcapngtool by hcxtools We are replacing it with their latest updated ones
Error: hcxpcaptool not found